/run/initialize

/gps/particle gamma
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/radius 9.525 mm
/gps/pos/centre 0. 0. -4000. mm
/gps/direction 0. 0. 1.
/gps/polarization 1. 0. 0.

/gps/ene/type Mono
/gps/ene/mono 7. MeV
# Using an arbitrary energy distribution
#/gps/ene/type User
#/gps/hist/type energy
#/gps/hist/point ENERGY INTENSITY
# ... add more energy-intensity pairs by repeated use of /gps/hist/point

/run/beamOn 10
