/run/initialize

/gps/particle gamma
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/radius 1.0 cm
/gps/pos/centre 0. 0. -300. mm
/gps/direction 0. 0. 1.

/gps/ene/type Mono
/gps/ene/mono 2. MeV

#/vis/open HepRepFile
#/vis/drawVolume
#/vis/viewer/flush
#/vis/scene/add/trajectories
#/vis/scene/add/hits
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/scene/endOfEventAction accumulate

/run/printProgress 1
/run/beamOn 4
