/run/initialize

#########################################################################
#
# AngularCorrelationGenerator can create multiple primary particles
# in a single event, where the angular distribution of the n-th particle
# is dependent on the emission direction of the (n-1)-th particle.
# This can be used, for example, to simulate correlated gamma-rays from
# an n-step decay of an excited nuclear state.
#
# The information about particles and their angular distribution is given
# step by step to AngularDistributionGenerator.
# 
# There are up to three possibilities to define the direction of emission:
#
# 1) /angcorr/direction X Y Z
#    This simply means that all particles of a kind are emitted in the same
#    direction. This command can only be used for the first particle in
#    the cascade.
# 2) /angcorr/relativeangle ANGLE UNIT
#    The particle will be emitted at an angle ANGLE relative to the
#    previous particle. Providing only one angle means that there is
#    still one degree of freedom left, which is randomly sampled.
#    This means that the particles will be emitted on the surface of
#    a cone with the emission angle of the previous particle as a
#    rotational symmetry axis.
# 3) /angcorr/nstates NSTATES
#    /angcorr/state1 STATE1
#    /angcorr/state2 STATE2
#    /angcorr/state3 STATE3
#    ...
#    [/angcorr/polarized IS_POLARIZED]
#    The particles will be emitted with an angular distribution that
#    is rotated in the same way as the emission direction of the previous
#    particle is rotated from the z-axis.
#########################################################################

# Define the number of steps in the cascade
/angcorr/steps 3

##################################
# Define the first step
##################################

# /angcorr/particle initiates the creation of a new cascade step. 
# The macro will fail if this is not the first command in a step definition.
/angcorr/particle gamma
/angcorr/energy 1. MeV
/angcorr/direction 0. 0. -1.

##################################
# Define the second step
##################################

/angcorr/particle geantino
/angcorr/energy 2. MeV
/angcorr/relativeangle 0. deg

##################################
# Define the third step
##################################

/angcorr/particle neutron
/angcorr/energy 3. MeV

/angcorr/nstates 3
/angcorr/state1 0.
/angcorr/state2 1.
/angcorr/state3 0.
# Polarization is already true by default
# but write it explicitly here for completeness.
/angcorr/polarized true

##################################
# Define the source volume
##################################
# The information about the source volumes is the same for all steps
# in the cascade, i.e. it is assumed that all particles are emitted
# from a common origin.
/angcorr/sourceX 0. mm
/angcorr/sourceY 0. mm
/angcorr/sourceZ 0. mm

/angcorr/sourceDX 2. mm
/angcorr/sourceDY 2. mm
/angcorr/sourceDZ 2. mm

/angcorr/sourcePV source

/run/beamOn 1000000
